title: Travis Rodgers | Central Virginia Web Developer

description: I build web applications. I also build websites, make them "pretty," and make them interactive.
url: http://travis.media

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title

gems:
  - jekyll-seo-tag

twitter:
  username: travisdotmedia
  
logo:
social:
  name: Travis Rodgers
  links:
    - https://twitter.com/travisdotmedia
    - https://github.com/rodgtr1
