title: Travis Rodgers
description: A Web Developer/Audio Engineer in Lynchburg, Virginia. I build web applications. I also build websites, make them "pretty," and make them interactive.
url: http://travis.media

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: travisdotmedia
  
logo: {{post.thumbnail}}
social:
  name: Travis Rodgers
  links:
    - https://twitter.com/travisdotmedia
    - https://github.com/rodgtr1
